@baseUrl = http://localhost:3000

### Health check
GET {{baseUrl}}/health

### Register (role OWNER)
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "owner1@eco.test",
  "password": "Password123!",
  "role": "OWNER"
}

### Register (role RENTER)
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "renter1@eco.test",
  "password": "Password123!",
  "role": "RENTER"
}

### Login (ambil JWT)
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "owner1@eco.test",
  "password": "Password123!"
}


